version: '3.8'

services:
  flask-image-generator:
    image: flask-image-generator:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
